name: hi
on: issue_comment

jobs:
  hello:
    env:
      fruit: apple
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      - name: check env
        run: |
          echo sha is: ${{ github.sha }}
          echo env is: ${{ env.my_env }}
          echo fruit step env is: $fruit
